INSERT INTO role (role) values
                            ('ATTENDEE'),
                            ('ORGANIZER');

INSERT INTO category (name) VALUES
                                ('Music'),
                                ('Sport'),
                                ('Art'),
                                ('Education'),
                                ('Technology'),
                                ('Food & Drink'),
                                ('Health & Wellness'),
                                ('Entertainment'),
                                ('Networking'),
                                ('Travel & Outdoor'),
                                ('Charity'),
                                ('Fashion');

INSERT INTO interest (name, category_id) VALUES
                                             ('Live Music', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Acoustic', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Jazz', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Rock', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Classical', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Pop', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Hip-Hop', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Electronic', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Country', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Blues', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Reggae', (SELECT id FROM category WHERE name = 'Music')),

                                             ('Football', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Basketball', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Tennis', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Baseball', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Soccer', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Golf', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Running', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Cycling', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Swimming', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Martial Arts', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Hiking', (SELECT id FROM category WHERE name = 'Sport')),

                                             ('Painting', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Sculpture', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Photography', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Drawing', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Digital Art', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Crafts', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Mixed Media', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Installation Art', (SELECT id FROM category WHERE name = 'Art')),

                                             ('Workshops', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Seminars', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Lectures', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Classes', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Online Courses', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Conferences', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Language Learning', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Professional Development', (SELECT id FROM category WHERE name = 'Education')),

                                             ('Coding Bootcamps', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Hackathons', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Tech Talks', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Product Launches', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Gadget Expos', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Software Workshops', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('AI and Machine Learning', (SELECT id FROM category WHERE name = 'Technology')),

                                             ('Wine Tasting', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Beer Tasting', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Cooking Classes', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Food Festivals', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Restaurant Week', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Farmers Markets', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Baking Workshops', (SELECT id FROM category WHERE name = 'Food & Drink')),

                                             ('Yoga', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Meditation', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Fitness Classes', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Wellness Retreats', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Mental Health Workshops', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Nutritional Seminars', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Spa Days', (SELECT id FROM category WHERE name = 'Health & Wellness')),

                                             ('Comedy Shows', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Theater', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Movie Screenings', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Magic Shows', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Circus', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Dance Performances', (SELECT id FROM category WHERE name = 'Entertainment')),

                                             ('Business Networking', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Social Meetups', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Alumni Events', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Industry Conferences', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Startup Pitches', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Speed Networking', (SELECT id FROM category WHERE name = 'Networking')),

                                             ('Camping', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Adventure Trips', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Wildlife Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Eco Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('City Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Cruises', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
INSERT INTO role (role) values
                            ('ATTENDEE'),
                            ('ORGANIZER');

INSERT INTO category (name) VALUES
                                ('Music'),
                                ('Sport'),
                                ('Art'),
                                ('Education'),
                                ('Technology'),
                                ('Food & Drink'),
                                ('Health & Wellness'),
                                ('Entertainment'),
                                ('Networking'),
                                ('Travel & Outdoor'),
                                ('Charity'),
                                ('Fashion');

INSERT INTO interest (name, category_id) VALUES
                                             ('Live Music', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Acoustic', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Jazz', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Rock', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Classical', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Pop', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Hip-Hop', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Electronic', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Country', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Blues', (SELECT id FROM category WHERE name = 'Music')),
                                             ('Reggae', (SELECT id FROM category WHERE name = 'Music')),

                                             ('Football', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Basketball', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Tennis', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Baseball', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Soccer', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Golf', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Running', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Cycling', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Swimming', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Martial Arts', (SELECT id FROM category WHERE name = 'Sport')),
                                             ('Hiking', (SELECT id FROM category WHERE name = 'Sport')),

                                             ('Painting', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Sculpture', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Photography', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Drawing', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Digital Art', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Crafts', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Mixed Media', (SELECT id FROM category WHERE name = 'Art')),
                                             ('Installation Art', (SELECT id FROM category WHERE name = 'Art')),

                                             ('Workshops', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Seminars', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Lectures', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Classes', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Online Courses', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Conferences', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Language Learning', (SELECT id FROM category WHERE name = 'Education')),
                                             ('Professional Development', (SELECT id FROM category WHERE name = 'Education')),

                                             ('Coding Bootcamps', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Hackathons', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Tech Talks', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Product Launches', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Gadget Expos', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('Software Workshops', (SELECT id FROM category WHERE name = 'Technology')),
                                             ('AI and Machine Learning', (SELECT id FROM category WHERE name = 'Technology')),

                                             ('Wine Tasting', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Beer Tasting', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Cooking Classes', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Food Festivals', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Restaurant Week', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Farmers Markets', (SELECT id FROM category WHERE name = 'Food & Drink')),
                                             ('Baking Workshops', (SELECT id FROM category WHERE name = 'Food & Drink')),

                                             ('Yoga', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Meditation', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Fitness Classes', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Wellness Retreats', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Mental Health Workshops', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Nutritional Seminars', (SELECT id FROM category WHERE name = 'Health & Wellness')),
                                             ('Spa Days', (SELECT id FROM category WHERE name = 'Health & Wellness')),

                                             ('Comedy Shows', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Theater', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Movie Screenings', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Magic Shows', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Circus', (SELECT id FROM category WHERE name = 'Entertainment')),
                                             ('Dance Performances', (SELECT id FROM category WHERE name = 'Entertainment')),

                                             ('Business Networking', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Social Meetups', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Alumni Events', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Industry Conferences', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Startup Pitches', (SELECT id FROM category WHERE name = 'Networking')),
                                             ('Speed Networking', (SELECT id FROM category WHERE name = 'Networking')),

                                             ('Camping', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Adventure Trips', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Wildlife Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Eco Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('City Tours', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Cruises', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),
                                             ('Road Trips', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),

                                             ('Fundraising Events', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Charity Walks/Runs', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Volunteering', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Charity Auctions', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Benefit Concerts', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Community Service Projects', (SELECT id FROM category WHERE name = 'Charity')),

                                             ('Fashion Shows', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Trunk Shows', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Fashion Weeks', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Style Workshops', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Design Exhibits', (SELECT id FROM category WHERE name = 'Fashion'));                                 ('Road Trips', (SELECT id FROM category WHERE name = 'Travel & Outdoor')),

                                             ('Fundraising Events', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Charity Walks/Runs', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Volunteering', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Charity Auctions', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Benefit Concerts', (SELECT id FROM category WHERE name = 'Charity')),
                                             ('Community Service Projects', (SELECT id FROM category WHERE name = 'Charity')),

                                             ('Fashion Shows', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Trunk Shows', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Fashion Weeks', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Style Workshops', (SELECT id FROM category WHERE name = 'Fashion')),
                                             ('Design Exhibits', (SELECT id FROM category WHERE name = 'Fashion'));